coverage:
  status:
    project:
      default:
        target: 90
        threshold: 2%
        if_ci_failed: success
    patch: off
ignore:
  - 'config/experience-cloud/**/*'
  - 'nebula-logger/recipes/**/*'
comment:
  behavior: new
