coverage:
    status:
        project:
            default:
                range: 75...100
                round: down
                precision: 2
                threshold: 1%
                if_ci_failed: success
        patch: off
ignore:
    - 'nebula-logger-recipes/**/*'
