/********************************************************************************************************
 * This file is part of the Apex Validation Rules project, released under the MIT License.              *
 * See LICENSE file or go to https://github.com/jongpie/RecordValidationRules for full license details. *
 *******************************************************************************************************/

@IsTest
private class LogRetentionRulesPlugin_Tests {
    @IsTest
    static void toDo() {
        System.assert(false, 'TODO - write some tests');
    }
}
