//------------------------------------------------------------------------------------------------//
// This file is part of the Nebula Logger project, released under the MIT License.                //
// See LICENSE file or go to https://github.com/jongpie/NebulaLogger for full license details.    //
//------------------------------------------------------------------------------------------------//

/**
 * @description Additional integration tests for orgs with Experience Sites (Communities) enabled
 */
@isTest
private class Logger_Tests_ExperienceSite {

    @isTest
    private static void it_should_test_something() {
        System.assert(false, 'TODO: write tests for users without a Network, users with a Network, and the guest user');
    }
}